name: lab4

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  name: Checkout code
         uses: actions/checkout@v2

      -  name: Set up Python
         uses: actions/setup-python@v2
         with: 
           python-version: 3.12

      -  name: Create virtual environment
         run: |
           python -m venv venv
           source venv/bin/activate

      -  name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           python -m pip install pytest
           python -m pip install pylint
           python -m pip install netifaces
           
      -  name: Print debugging information
         run: |
           echo "Python version: $(python --version)"
           echo "Working Directory: $(pwd)"
           echo "Contents of Working Directory: $(ls -l)"
           echo "Contents of site-packages: $(ls -l venv/bin/python*/site-packages)"

      -  name: Run tests for Task 1
         run: |
           pytest

      -  name: Run tests for Task 2
         run: |
           pylint task2.py
